### ISSUE TITLE
Not working properly in android 9

### ISSUE THREAD

**Issue by UmairAhmed420** [NlptechProduct/Android-Keyboard#151]

**Comment by UmairAhmed420** [comment]
is this sample project supported android 9 ?

**Comment by NlptechProduct** [comment]
Hi @UmairAhmed420 , what's the problem you encountered on Android 9 devices?

**Comment by UmairAhmed420** [comment]
the problem is that when i click on neutral strip options they are not working .... for example i click keyboardMenuWiget ... is doesnt show its view and keyboard is just behaving like normal keyboard

**Comment by NlptechProduct** [comment]
Hi Umair Ahmed,

Are you using the latest version of code?

The problem you described cannot be reproduced on our devices. Can you show us a video of this? Thanks.

**Comment by UmairAhmed420** [comment]
i just made a clone of ur github project and used it. and for video .... can you give me your email address so i can send you video of problem

**Comment by NlptechProduct** [comment]
@UmairAhmed420 You can send the video to zengine@nlptech.com
Thanks.

**Comment by wasi92** [comment]
how to change pakage name ...?

**Comment by wasi92** [comment]
how to change pakage name place video likn send me

**Comment by NlptechProduct** [comment]
@wasi92 You can change package name by changing applicationId in app/build.gradle file

**Comment by wasi92** [comment]
place send me likn video how to change pakage name

**Comment by wasi92** [comment]
how don't change pakage name help me please

**Comment by wasi92** [comment]
how change pakage name help me please
