### ISSUE TITLE
getting unnessasary space while typing in german language

### ISSUE THREAD

**Issue by pondeepakponraj** [NlptechProduct/Android-Keyboard#164]
![english](https://user-images.githubusercontent.com/59448300/71680336-cc663b00-2daf-11ea-9b02-58360c34ae89.png)
![german](https://user-images.githubusercontent.com/59448300/71680337-cc663b00-2daf-11ea-8326-95549e2faca7.png)

**Comment by pondeepakponraj** [comment]
How to avoid this spacing.

**Comment by NlptechProduct** [comment]
@pondeepakponraj Hi, thanks for your feedback. But I can't reproduce this. Can you tell me more details?

**Comment by pondeepakponraj** [comment]
i have enabled english first i did not got the spaces while typing ü and while enabling only german and type ü one space is getting added always, how to overcome without adding this space

**Comment by NlptechProduct** [comment]
@pondeepakponraj Thanks. We have successfully located the bug. We'll fix it soon.

**Comment by gdafzalkhan99** [comment]
hello @NlptechProduct  if possible please provide your email address?

**Comment by pondeepakponraj** [comment]
Can you Please advise the solution for this. I need to fix this very soon as i am facing a big problem because of this.
