### ISSUE TITLE
App crashes on change key border  switch

### ISSUE THREAD

**Issue by mitsubisu** [NlptechProduct/Android-Keyboard#171]
Hello, I download source code again today and see that you add new themes for keyboard, Thanks for it. I loved to use it, but I checked one of them creates crashes on the app. I recorded that and upload that video for your understanding thanks

[https://drive.google.com/file/d/1BnspjCJKwsSPUEzKQyAJZ4jww2FARJa6/view?usp=sharing](url)

**Comment by NlptechProduct** [comment]
Fixed.
