### ISSUE TITLE
Classes not found

### ISSUE THREAD

**Issue by zainriaz** [NlptechProduct/Android-Keyboard#60]
The below classes package not found in project

import com.nlptech.common.constant.Constants;
import com.nlptech.inputmethod.latin.SuggestedWords;
import com.nlptech.inputmethod.latin.utils.TypefaceUtils;

with zengine edition
implementation "com.nlptech.zengine:keyboardkernel:1.1.0"

**Comment by kote6363** [comment]
Which zengine edition is in build.gradle of your project？

**Comment by zainriaz** [comment]
My project using 
implementation "com.nlptech.zengine:keyboardkernel:1.1.0" in build.gradle.

**Comment by kote6363** [comment]
Please clean project and sync again,Maybe there is something wrong with downloading zengine.

**Comment by NlptechProduct** [comment]
@zainriaz If you are using command line to build the project, please use Gradle Wrapper. A higher version of local gradle may cause build failed on some occasion.

**Comment by NlptechProduct** [comment]
This issue is solved in the latest version.
